vectara:
  corpus_key: gdrive
  reindex: true
  create_corpus: false

crawling:
  crawler_type: gdrive

gdrive_crawler:
  delegated_users:
    - <add email id>
    - <add email id>
  credentials_file: /path/to/credentials.json
